spring:
  profiles:
    active: instanceOne
  application:
    name: eureka-service

eureka:
  client:
    #不向注册中心注册自己
    register-with-eureka: false
  server:
    enable-self-preservation: false
    #是否从eureka服务器获取注册信息，这里不需要
    fetch-registry: false
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS

---

spring:
  profiles: instanceOne

server:
  port: 7777

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7778/eureka/

---
spring:
  profiles: instanceTwo

server:
  port: 7778

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/