eureka:
  client:
    serviceUrl:
      # 注明自己的服务注册中心的地址
      defaultZone: http://localhost:7777/eureka/
server:
  port: 8005
spring:
  application:
    name: service-feign
# feign调用模式下打开断路器
feign:
   hystrix:
     enabled: true