eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/
server:
  port: 8004
spring:
  application:
    name: service-ribbon
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS
